### ISSUE TITLE
This repository is an Unvanquished submodule.

### ISSUE THREAD

**Issue by illwieckz** [DaemonEngine/recastnavigation#2]
This repository is an Unvanquished submodule.

I guess we can move it back to https://github.com/Unvanquished organization.

**Comment by necessarily-equal** [comment]
Maybe we can fix that as we move the repositories to $somewhere_else

**Comment by ghost** [comment]
and this makes it harder to do a PR for no reason. Please move it to proper organisation, in case I have to do this anew.

**Comment by slipher** [comment]
Probably we would be better off moving it into the Unvanquished repo (as in, it will no longer be a submodule). Recast has a [made-to-be-forked](https://unvanquished.net/building-a-community-as-a-service/) design philosophy, and upstream is long moribund. As soon as anyone actually manages to understand how it works, I'm sure we'll have a lot of customizations to make.

**Comment by ghost** [comment]
It's as moribund than unvanquished was 2 years ago though.

As for the "designed to be forked", well, that's exactly why I sent them a PR to make the config var configurable without having to be forked. I'll probably send them more like that when I see more things that would benefit from this.

**Comment by illwieckz** [comment]
In fact https://github.com/Unvanquished/recastnavigation already works because it redirects there.

The reason why is that before this repository was in Unvanquished organization. It moved there when we extracted the engine, and at the time we extracted the engine the navmesh code was in engine.

GitHub keeps track of repository moving/renaming, so we can move it anytime without fearing a breakage in submodules fetch. As far as I know, even opened and unmerged PR are properly migrated while moving a repository from one organization to another. So let's just do this.

**Comment by illwieckz** [comment]
Done.

**Comment by illwieckz** [comment]
GitHub should take care of properly redirecting the requests done to the old DæmonEngine path.

If someone wants to cleanup the paths in his local clone to not make use of redirects, he may do that:

```sh
cd 'Unvanquished'
git checkout 'master'
git pull
git submodule update --init --recursive
git submodule set-url 'libs/recastnavigation' 'https://github.com/Unvanquished/recastnavigation.git'
git -C 'libs/recastnavigation' remote set-url 'origin' 'https://github.com/Unvanquished/recastnavigation.git'
```

**Comment by ghost** [comment]
thx
